name: cicd-1
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [master]
    paths:
      - src/**
      - build.gradle
  push:
    branches: [ master ]
    paths:
      - src/**
      - build.gradle
      - .github/workflows/cicd-1.yaml

jobs:
  test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  image-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: [image-build]
    steps:
      - name: checkout
        uses: actions/checkout@v4