name: cicd
on:
  push:
    branches: [ master ]
    paths:
      - src/**
      - .github/workflows/cicd-1.yaml
      - Dockerfile

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Github 리포지토리에서 소스 코드 가져오기
      - name: checkout the code
        uses: actions/checkout@v4
      # Java 설정 추가
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      # 의존성 설치 시간 단축을 위한 Gradle 패키지 캐싱
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # 권한 설정
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      # 단위 테스트 실행
      - name: Run tests
        run: ./gradlew test
