name: cicd-1
on:
  pull_request:
    types: [ opened, synchronize, closed ]
    branches: [ master ]
    paths:
      - src/**
      - build.gradle
  push:
    branches: [ master ]
    paths:
      - src/**
      - build.gradle
      - .github/workflows/cicd-1.yaml

jobs:
  test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize'))
    runs-on: ubuntu-latest
    steps:
      # Github 리포지토리에서 소스 코드 가져오기
      - name: checkout the code
        uses: actions/checkout@v4
      # 자바 버전 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      # 의존성 설치 시간 단축을 위한 Gradle 패키지 캐싱
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      # 단위 테스트 실행
      - name: Run tests
        run: ./gradlew test

  image-build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: [ image-build ]
    steps:
      - name: checkout
        uses: actions/checkout@v4